import { IProjects } from '../interfaces/IProjects.interface';

export const CPROJECTS_CONSTANT: IProjects[] = [
  {
    id: '1',
    name: 'Gestor de Tareas',
    description: 'Transformando ideas en soluciones digitales innovadoras.',
    valoraciones: 4.5,
    imgUrl: 'https://example.com/task-manager.jpg',
    imgs: [
      'https://example.com/task-manager1.jpg',
      'https://example.com/task-manager2.jpg',
    ],
    createdAt: '2023-01-15',
    lenguaje: 'TypeScript',
    tecnologia: 'Angular',
    database: 'SQL Server',
    lenguajes: ['TypeScript', 'JavaScript'],
    tecnologias: ['Angular', 'SQL Server', 'Bootstrap'],
    icon: 'https://example.com/task-manager-icon.png',
  },
  {
    id: '2',
    name: 'Aplicación de Comercio Electrónico',
    description:
      'Proyectos que combinan creatividad y tecnología para resolver problemas reales.',
    valoraciones: 4.8,
    imgUrl: 'https://example.com/e-commerce.jpg',
    imgs: [
      'https://example.com/e-commerce1.jpg',
      'https://example.com/e-commerce2.jpg',
    ],
    createdAt: '2022-11-10',
    lenguaje: 'Dart',
    tecnologia: 'Flutter',
    database: 'Firebase',
    lenguajes: ['Dart'],
    tecnologias: ['Flutter', 'Firebase'],
    icon: 'https://example.com/e-commerce-icon.png',
  },
  {
    id: '3',
    name: 'Red Social',
    description:
      'Experiencias digitales diseñadas para impactar y mejorar vidas.',
    valoraciones: 4.7,
    imgUrl: 'https://example.com/social-network.jpg',
    imgs: [
      'https://example.com/social-network1.jpg',
      'https://example.com/social-network2.jpg',
    ],
    createdAt: '2023-03-22',
    lenguaje: 'JavaScript',
    tecnologia: 'Express',
    database: 'MongoDB',
    lenguajes: ['JavaScript', 'HTML', 'CSS'],
    tecnologias: ['Express', 'Node.js', 'MongoDB'],
    icon: 'https://example.com/social-network-icon.png',
  },
  // {
  //   id: '4',
  //   name: 'Sistema de Gestión Escolar',
  //   description: 'Construyendo el futuro a través del desarrollo de software.',
  //   valoraciones: 4.6,
  //   imgUrl: 'https://example.com/school-management.jpg',
  //   imgs: [
  //     'https://example.com/school-management1.jpg',
  //     'https://example.com/school-management2.jpg',
  //   ],
  //   createdAt: '2023-05-15',
  //   lenguaje: 'TypeScript',
  //   tecnologia: 'NestJS',
  //   database: 'PostgreSQL',
  //   lenguajes: ['TypeScript', 'JavaScript'],
  //   tecnologias: ['NestJS', 'PostgreSQL', 'TypeORM'],
  //   icon: 'https://example.com/school-management-icon.png',
  // },
  // {
  //   id: '5',
  //   name: 'Aplicación de Gestión de Inventarios',
  //   description:
  //     'Proyectos que reflejan mi dedicación al detalle y la excelencia técnica.',
  //   valoraciones: 4.9,
  //   imgUrl: 'https://example.com/inventory-management.jpg',
  //   imgs: [
  //     'https://example.com/inventory-management1.jpg',
  //     'https://example.com/inventory-management2.jpg',
  //   ],
  //   createdAt: '2022-08-21',
  //   lenguaje: 'C#',
  //   tecnologia: 'ASP.NET',
  //   database: 'SQL Server',
  //   lenguajes: ['C#', 'JavaScript'],
  //   tecnologias: ['ASP.NET', 'SQL Server', 'Entity Framework'],
  //   icon: 'https://example.com/inventory-management-icon.png',
  // },
  // {
  //   id: '6',
  //   name: 'E-commerce Platform',
  //   description:
  //     'Proyectos que combinan creatividad y tecnología para resolver problemas reales.',
  //   valoraciones: 4.8,
  //   imgUrl: 'https://example.com/e-commerce.jpg',
  //   imgs: [
  //     'https://example.com/e-commerce1.jpg',
  //     'https://example.com/e-commerce2.jpg',
  //   ],
  //   createdAt: '2022-11-10',
  //   lenguaje: 'Python',
  //   tecnologia: 'Django',
  //   database: 'PostgreSQL',
  //   lenguajes: ['Python', 'JavaScript'],
  //   tecnologias: ['Django', 'Bootstrap', 'PostgreSQL'],
  //   icon: 'https://example.com/e-commerce-icon.png',
  // },
];
