import { TypeSkillEnum } from 'src/app/shared/utils/enum/type-skill.enum';
import { IProjects } from '../interfaces/IProjects.interface';

export const CPROJECTS_CONSTANT: IProjects[] = [
  {
    id: 1,
    name: 'Sistema de Venta de Pasajes Online - Emtrafesa',
    description:
      'Sistema de venta de pasajes online para la empresa Emtrafesa, que permite a los usuarios comprar boletos de manera rápida y sencilla.',
    valoraciones: 4.5,
    imgUrl: 'assets/projects/emtrafesa/emtrafesa_home.webp',
    imgs: [
      'assets/projects/emtrafesa/emtrafesa_home.webp',
      'assets/projects/emtrafesa/emtrafesa_about.webp',
      'assets/projects/emtrafesa/emtrafesa_flota.webp',
      'assets/projects/emtrafesa/emtrafesa_sucursales.webp',
    ],
    createdAt: '2023-01-15',
    lenguaje: 'TypeScript',
    tecnologia: {
      id: 1,
      name: 'Angular',
      description:
        'Framework para construir aplicaciones web de una sola página.',
      imgUrl: 'https://example.com/angular.webp',
      type: TypeSkillEnum.FRONTEND,
    },
    database: 'SQL Server',
    lenguajes: ['TypeScript', 'JavaScript'],
    tecnologias: [
      'Angular',
      'NestJs',
      'SQL Server',
      'MongoDB',
      'PrimeNg',
      'Primeflex',
    ],
    icon: 'https://example.com/task-manager-icon.webp',
    impacto: [
      // 'Aumento del 30% en las ventas online en el primer mes de implementación.',
      // 'Reducción del tiempo de compra en un 50%.',
      // 'Mejora en la satisfacción del cliente con un aumento del 20% en las valoraciones positivas.',
      'Facilitación de la compra de pasajes desde cualquier lugar y en cualquier momento.',
      'Reducción de la carga de trabajo del personal de ventas al automatizar el proceso de compra.',
      'Aumento de la eficiencia operativa al reducir el tiempo de espera para los clientes.',
      'Mejora en la experiencia del cliente al ofrecer una plataforma fácil de usar.',
      'Aumento de la visibilidad de la empresa al ofrecer un servicio moderno y accesible.',
    ],
    retosSuperados: [
      'Integración con el sistema de gestión de flota existente.',
      'Integracion con microservicios para la gestión de pagos y reservas.',
      'Implementacion de seguridad de tokens para proteger la información del cliente.',
      'Desarrollo de una interfaz de usuario intuitiva y fácil de usar.',
      'Uso de formularios reactivos para la validación de datos en tiempo real.',
      'Implementación de un sistema de gestión de errores para mejorar la experiencia del usuario.',
    ],
    link: 'https://emtrafesa.com',
  },
  {
    id: 2,
    name: 'Sistema de Gestion Administrativa - Andeskar',
    description:
      'Sistema de gestión administrativa para la empresa Andeskar, que permite a los usuarios gestionar sus operaciones diarias de manera eficiente.',
    valoraciones: 4.8,
    imgUrl: 'assets/projects/andeskar/andeskar_bizlink.webp',
    imgs: [
      'assets/projects/andeskar/andeskar_bizlink.webp',
      'assets/projects/andeskar/andeskar_dashboard.webp',
      'assets/projects/andeskar/andeskar_detalle_orden.webp',
      'assets/projects/andeskar/andeskar_nueva_orden.webp',
      'assets/projects/andeskar/andeskar_nueva_trayectoria.webp',
      'assets/projects/andeskar/andeskar_ordenes_individuales.webp',
      'assets/projects/andeskar/andeskar_pagos.webp',
      'assets/projects/andeskar/andeskar_pdf_orden.webp',
    ],
    createdAt: '2022-11-10',
    lenguaje: 'TypeScript',
    tecnologia: {
      id: 1,
      name: 'Angular',
      description:
        'Framework para construir aplicaciones web de una sola página.',
      imgUrl: 'https://example.com/angular.webp',
      type: TypeSkillEnum.FRONTEND,
    },
    database: 'Sql Server',
    lenguajes: ['TypeScript', 'JavaScript'],
    tecnologias: ['Angular','.Net Core', 'SQL Server', 'PrimeNg', 'Primeflex', 'PdfMake', 'StencilJs'],
    icon: 'https://example.com/e-commerce-icon.webp',
    impacto: [
      'Aumento del 40% en la eficiencia operativa al automatizar procesos manuales.',
      'Reducción del tiempo de procesamiento de órdenes en un 30%.',
      'Facilitación de la gestión de operaciones diarias desde una sola plataforma.',
      'Reducción de errores humanos al automatizar el proceso de gestión de órdenes.',
      'Aumento de la visibilidad de la empresa al ofrecer un servicio moderno y accesible.',
    ],
    retosSuperados: [
      'Integracion con RENIEC para la validación de datos de clientes.',
      'Integracion con Bizlink para la emición de comprobantes electrónicos.',
      'Integracion API REST a medida para la gestion de ordenes, comprobantes, pagos, embarques, trayectorias, reportes, etc.',
      'Implementacion de seguridad de tokens para proteger la información del cliente.',
      'Uso de formularios reactivos para la validacion y respuesta de datos en tiempo real.',
      'Uso de interceptores para la gestión de errores, autenticación y carga de datos.',
      'Uso de Docker para la creación de contenedores y despliegue en la nube.',
      'Uso de StencilJs para la creación de componentes reutilizables y escalables.',
      'Creacion de pipes, directivas y servicios para la gestión de datos y la creación de componentes reutilizables.',
      'Uso de PdfMake para la generación de documentos PDF.',
      'Uso de PrimeNg para la creación de una interfaz de usuario moderna y atractiva.',
      'Despliegue en Google Cloud para garantizar la disponibilidad y escalabilidad del sistema usando CI/CD.',
    ],
    link: 'https://andeskar.com',
  },
  {
    id: 3,
    name: 'Dicta Colombia - Students',
    description:
      'Sistema de gestión de estudiantes para la plataforma Dicta Colombia, que permite a los usuarios gestionar sus cursos y estudiantes de manera sencilla.',
    valoraciones: 4.7,
    imgUrl: 'assets/projects/dicta/dicta_home.webp',
    imgs: [
      'assets/projects/dicta/dicta_home.webp',
      'assets/projects/dicta/dicta_login.webp',
    ],
    createdAt: '2023-03-22',
    lenguaje: 'JavaScript',
    tecnologia: {
      id: 1,
      name: 'Angular',
      description:
        'Framework para construir aplicaciones web de una sola página.',
      imgUrl: 'https://example.com/angular.webp',
      type: TypeSkillEnum.FRONTEND,
    },
    database: 'MongoDB',
    lenguajes: ['JavaScript', 'TypeScript'],
    tecnologias: ['Angular','.Net Core', 'NestJs', 'Node.js', 'MongoDB', 'SQL Server', 'PrimeNg', 'Primeflex', 'StencilJs'],
    icon: 'https://example.com/social-network-icon.webp',
    impacto: [
      'Aumento de la visibilidad de la empresa al ofrecer interfaces modernas y accesibles.',
      'Facilitación de la gestión de estudiantes desde una sola plataforma.',
      'Facilitación de la gestión de cursos desde una sola plataforma.',
      'Reducción de errores humanos al automatizar el proceso de gestión de estudiantes.',
      'Reduccion de tiempo de proceso para crear nuevos planetas, galaaxias y cursos que no solo afectan a Dicta Colombia - Students, sino a todas las aplicaciones de Dicta.',
      'Aumento de la eficiencia operativa al automatizar procesos manuales.',
    ],
    retosSuperados: [
      'Integracion con dos APIS REST a medidad para la gestion de autentificacion, pagos y creacion de planetas',
      'Integracion con el sitema de pagos de Stripe',
      'Uso de StencilJs para la creación de componentes reutilizables y escalables.',
      'Uso de formularios reactivos para la validacion y respuesta de datos en tiempo real.',
      'Uso de Primeng y Primeflex para la creación de una interfaz de usuario moderna y atractiva.',
      'Uso de Microsoft Azure Blob Storage para la gestión de archivos y documentos.',
      'Presentacion de prototipo en donde se muestra una arquitectura basada en microfrontend para integrar la aplicacion de Dicta Colombia - Students con la aplicacion Universo Dicta.',
    ],
    link: 'https://dicta.com.co',
  },
  // {
  //   id: 4,
  //   name: 'Sistema de Gestión Escolar',
  //   description: 'Construyendo el futuro a través del desarrollo de software.',
  //   valoraciones: 4.6,
  //   imgUrl:
  //     'https://chayxe.vn/wp-content/uploads/2023/02/yamaha-yzf-r7-2023-ra-mat-voi-mau-trang-cuc-ngau-chayxe-vn-3.jpg',
  //   imgs: [
  //     'https://example.com/school-management1.jpg',
  //     'https://example.com/school-management2.jpg',
  //   ],
  //   createdAt: '2023-05-15',
  //   lenguaje: 'TypeScript',
  //   tecnologia: {
  //     id: 2,
  //     name: 'NestJs',
  //     description:
  //       'Framework para construir aplicaciones del lado del servidor con TypeScript.',
  //     imgUrl: 'assets/skills/nestjs.svg',
  //     type: TypeSkillEnum.BACKEND,
  //   },
  //   database: 'PostgreSQL',
  //   lenguajes: ['TypeScript', 'JavaScript'],
  //   tecnologias: ['NestJS', 'PostgreSQL', 'TypeORM'],
  //   icon: 'https://example.com/school-management-icon.webp',
  // },
  // {
  //   id: 5,
  //   name: 'Aplicación de Gestión de Inventarios',
  //   description:
  //     'Proyectos que reflejan mi dedicación al detalle y la excelencia técnica.',
  //   valoraciones: 4.9,
  //   imgUrl: 'https://lucero.com.pe/wp-content/uploads/2023/03/3-11.webp',
  //   imgs: [
  //     'https://example.com/inventory-management1.jpg',
  //     'https://example.com/inventory-management2.jpg',
  //   ],
  //   createdAt: '2022-08-21',
  //   lenguaje: 'C#',
  //   tecnologia: {
  //     id: 7,
  //     name: '.Net Core',
  //     description:
  //       'Framework de desarrollo de aplicaciones multiplataforma de Microsoft.',
  //     imgUrl: 'assets/skills/net.svg',
  //     type: TypeSkillEnum.BACKEND,
  //   },
  //   database: 'SQL Server',
  //   lenguajes: ['C#', 'JavaScript'],
  //   tecnologias: ['ASP.NET', 'SQL Server', 'Entity Framework'],
  //   icon: 'https://example.com/inventory-management-icon.webp',
  // },
];
